"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/public/styles/font.css";
import "@/public/styles/index.css";
import "@/public/styles/tailwind.css";
import { Provider } from "react-redux";
import { store } from "@/store/store";

type CustomMetadata = {
  title: string;
  description: string;
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const metadata: CustomMetadata = {
    title: "Home",
    description: "Generated by create next app",
  };
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <Provider store={store}>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  );
}
